[flake8]
max-line-length = 88

[tool.poetry]
name = "pyurbandict"
version = "0.2.2"
description = "Python wrapper for the Urban Dictionary API."
authors = ["Vitaman02"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
